# Generated by Django 5.2.4 on 2025-07-21 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_recentclassroom_recentsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.subject'),
        ),
    ]
